name: 'Sync init'
description: 'Git initialises and clears a directory to track a separate branch on the same git repo'
inputs:
  syncDir:
    description: 'Directory to git init'
    default: sync
    required: true
  syncBranch:
    description: 'Branch to track in Directory'
    default: sync
    required: true
  token:
    description: >
      Personal access token (PAT) used to clone sync branch.
    default: ${{ github.token }}
    required: true
runs:
  using: "composite"
  steps:
    - name: Download release
      shell: bash
      run: |
        echo "#################################################"
        echo "Changing directory to 'PUBLISH_DIR' ${PUBLISH_DIR} ..."
        mkdir -p ${PUBLISH_DIR}
        cd ${PUBLISH_DIR}
        ls -lah

        echo '=================== Initialising Sync branch ==================='
        remote_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git init
        git remote add deploy ${remote_repo}
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git fetch deploy
        git checkout --track deploy/${PUBLISH_BRANCH}|| git checkout --orphan ${PUBLISH_BRANCH}
        cd ../

        # clear the ${PUBLISH_DIR} while keeping the `.git` folder
        mkdir -p deleteme 
        mv ${PUBLISH_DIR}/* deleteme || echo "${PUBLISH_DIR} is already empty"
        rm -rf deleteme
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        PUBLISH_DIR: ${{ inputs.syncDir }}
        PUBLISH_BRANCH: ${{ inputs.syncBranch }}
